# Generated by Django 5.2.8 on 2026-01-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("author", models.TextField()),
                ("text", models.TextField()),
                ("date", models.DateTimeField(db_column="date")),
                ("likes", models.IntegerField()),
                ("image", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "comments",
            },
        ),
    ]
