# Generated by Django 5.2.8 on 2026-01-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
